apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ce-saas
  template:
    metadata:
      labels:
        app: ce-saas
    spec:
      containers:
        - name: ce-saas
          image: ghcr.io/g-code-7/ce-saas-sample
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ghcr-login-secret
