apiVersion: v1
kind: Service
metadata:
  name: saas-nodeport
  labels:
    app: ce-saas
spec:
  type: NodePort
  selector:
    app: ce-saas
  ports:
    - protocol: TCP
      port: 80        # Service port inside the cluster
      targetPort: 80  # Pod container port
      nodePort: 30080 # External port on each node (range 30000-32767)
